SQLALCHEMY_DATABASE_URI: "sqlite:///ticketdb.db"
SQLALCHEMY_TRACK_MODIFICATIONS: false
JWT_SECRET_KEY: "your_secret_key"
CACHE_TYPE: "redis"
CACHE_REDIS_URL: "redis://localhost:6379/0"
BROKER_URL: "redis://localhost:6379/1"
RESULT_BACKEND: "redis://localhost:6379/2"

CELERY_BROKER_URL: "redis://localhost:6379/1"
CELERY_RESULT_BACKEND: "redis://localhost:6379/2"


CORS_SUPPORTS_CREDENTIALS: true

DEBUG: true
